<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LE119FM" failures="1" tests="1" name="TestRemote" time="39.418" errors="0" timestamp="2023-06-12T15:53:40 IST">
  <testcase classname="test.Test1" name="test1" time="1.264">
    <failure type="java.lang.AssertionError" message="expected [https://demo.actitime.com/user/submit_tt.do] but found [https://demo.actitime.com/login.do]">
      <![CDATA[java.lang.AssertionError: expected [https://demo.actitime.com/user/submit_tt.do] but found [https://demo.actitime.com/login.do]
at test.Test1.test1(Test1.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
</testsuite> <!-- TestRemote -->
